import { unstable_setRequestLocale } from "next-intl/server";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: {locale: string}
}) {
  unstable_setRequestLocale(params.locale);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
